### ISSUE TITLE
分支如何建

### ISSUE THREAD

**Issue by cjiayang** [yifanzheng/yifanzheng.github.io#1]
你好，请问你的源码分支是如何创建的？

**Comment by yifanzheng** [comment]
你好，GitHub上 有个 **Branch** 按钮，点击后输入分支名称，然后按 “Enter” 键，就可以创建分支啦。
![Snipaste_2020-05-08_12-19-15](https://user-images.githubusercontent.com/22571230/81369917-5dff0400-9126-11ea-9ec9-7a676173e5c5.png)

**Comment by cjiayang** [comment]
我的问题应该改下，怎样把hexo源码传到backup分支上的呢？
不过我已经在网上找到答案了，参考了以下两个回答
https://www.jianshu.com/p/0b1fccce74e0
https://www.zhihu.com/question/21193762
还是多谢你的回答^-^

**Comment by yifanzheng** [comment]
> 我的问题应该改下，怎样把hexo源码传到backup分支上的呢？
> 不过我已经在网上找到答案了，参考了以下两个回答
> https://www.jianshu.com/p/0b1fccce74e0
> https://www.zhihu.com/question/21193762
> 还是多谢你的回答^-^

其实不用那么复杂。当你创建好 backup 分支后，直接切换到 backup 分支，在这个分支上进行编辑。你的部署文件 config.yml 里已经配置好了博客的部署地址是 master 分支。所以，你直接在 backup 分支上操作就好了，然后使用 git 命令上传，之后再使用 hexo 命令部署，部署的文件会自动上传到 master 分支。
